{
 "title": "Api Rest Twitter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total de Requests por Minuto",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status=\"200\"}[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Quantidade de Erros - API Rest Twitter",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total{status!=\"200\"}[1m])",
     "legendFormat": "HTTP{{status}}"
    }
   ]
  },
  {
   "title": "Container - Consumo de CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"services\",instance=\"api_rest_twitter:5000\"}[1m])"
    }
   ]
  },
  {
   "title": "Latência - Tempo de Execução por Request",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[1m]) ",
     "legendFormat": "HTTP {{le}}"
    }
   ]
  },
  {
   "title": "Container - Consumo de Memória",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"services\",instance=\"api_rest_twitter:5000\"}"
    }
   ]
  }
 ]
}